// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBasePricesParams creates a new GetBasePricesParams object
// with the default values initialized.
func NewGetBasePricesParams() *GetBasePricesParams {
	var ()
	return &GetBasePricesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBasePricesParamsWithTimeout creates a new GetBasePricesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBasePricesParamsWithTimeout(timeout time.Duration) *GetBasePricesParams {
	var ()
	return &GetBasePricesParams{

		timeout: timeout,
	}
}

// NewGetBasePricesParamsWithContext creates a new GetBasePricesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBasePricesParamsWithContext(ctx context.Context) *GetBasePricesParams {
	var ()
	return &GetBasePricesParams{

		Context: ctx,
	}
}

// NewGetBasePricesParamsWithHTTPClient creates a new GetBasePricesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBasePricesParamsWithHTTPClient(client *http.Client) *GetBasePricesParams {
	var ()
	return &GetBasePricesParams{
		HTTPClient: client,
	}
}

/*GetBasePricesParams contains all the parameters to send to the API endpoint
for the get base prices operation typically these are written to a http.Request
*/
type GetBasePricesParams struct {

	/*AcceptDatetimeFormat
	  Format of DateTime fields in the request and response.

	*/
	AcceptDatetimeFormat *string
	/*Authorization
	  The authorization bearer token previously obtained by the client

	*/
	Authorization string
	/*Time
	  The time at which the desired price for each instrument is in effect. The current price for each instrument is returned if no time is provided.

	*/
	Time *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get base prices params
func (o *GetBasePricesParams) WithTimeout(timeout time.Duration) *GetBasePricesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get base prices params
func (o *GetBasePricesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get base prices params
func (o *GetBasePricesParams) WithContext(ctx context.Context) *GetBasePricesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get base prices params
func (o *GetBasePricesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get base prices params
func (o *GetBasePricesParams) WithHTTPClient(client *http.Client) *GetBasePricesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get base prices params
func (o *GetBasePricesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAcceptDatetimeFormat adds the acceptDatetimeFormat to the get base prices params
func (o *GetBasePricesParams) WithAcceptDatetimeFormat(acceptDatetimeFormat *string) *GetBasePricesParams {
	o.SetAcceptDatetimeFormat(acceptDatetimeFormat)
	return o
}

// SetAcceptDatetimeFormat adds the acceptDatetimeFormat to the get base prices params
func (o *GetBasePricesParams) SetAcceptDatetimeFormat(acceptDatetimeFormat *string) {
	o.AcceptDatetimeFormat = acceptDatetimeFormat
}

// WithAuthorization adds the authorization to the get base prices params
func (o *GetBasePricesParams) WithAuthorization(authorization string) *GetBasePricesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get base prices params
func (o *GetBasePricesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithTime adds the time to the get base prices params
func (o *GetBasePricesParams) WithTime(time *string) *GetBasePricesParams {
	o.SetTime(time)
	return o
}

// SetTime adds the time to the get base prices params
func (o *GetBasePricesParams) SetTime(time *string) {
	o.Time = time
}

// WriteToRequest writes these params to a swagger request
func (o *GetBasePricesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AcceptDatetimeFormat != nil {

		// header param Accept-Datetime-Format
		if err := r.SetHeaderParam("Accept-Datetime-Format", *o.AcceptDatetimeFormat); err != nil {
			return err
		}

	}

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Time != nil {

		// query param time
		var qrTime string
		if o.Time != nil {
			qrTime = *o.Time
		}
		qTime := qrTime
		if qTime != "" {
			if err := r.SetQueryParam("time", qTime); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
