// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// CancellableOrderType The type of the Order.
// swagger:model CancellableOrderType
type CancellableOrderType string

const (

	// CancellableOrderTypeLIMIT captures enum value "LIMIT"
	CancellableOrderTypeLIMIT CancellableOrderType = "LIMIT"

	// CancellableOrderTypeSTOP captures enum value "STOP"
	CancellableOrderTypeSTOP CancellableOrderType = "STOP"

	// CancellableOrderTypeMARKETIFTOUCHED captures enum value "MARKET_IF_TOUCHED"
	CancellableOrderTypeMARKETIFTOUCHED CancellableOrderType = "MARKET_IF_TOUCHED"

	// CancellableOrderTypeTAKEPROFIT captures enum value "TAKE_PROFIT"
	CancellableOrderTypeTAKEPROFIT CancellableOrderType = "TAKE_PROFIT"

	// CancellableOrderTypeSTOPLOSS captures enum value "STOP_LOSS"
	CancellableOrderTypeSTOPLOSS CancellableOrderType = "STOP_LOSS"

	// CancellableOrderTypeTRAILINGSTOPLOSS captures enum value "TRAILING_STOP_LOSS"
	CancellableOrderTypeTRAILINGSTOPLOSS CancellableOrderType = "TRAILING_STOP_LOSS"
)

// for schema
var cancellableOrderTypeEnum []interface{}

func init() {
	var res []CancellableOrderType
	if err := json.Unmarshal([]byte(`["LIMIT","STOP","MARKET_IF_TOUCHED","TAKE_PROFIT","STOP_LOSS","TRAILING_STOP_LOSS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cancellableOrderTypeEnum = append(cancellableOrderTypeEnum, v)
	}
}

func (m CancellableOrderType) validateCancellableOrderTypeEnum(path, location string, value CancellableOrderType) error {
	if err := validate.Enum(path, location, value, cancellableOrderTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this cancellable order type
func (m CancellableOrderType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateCancellableOrderTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
