// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ClientRequestID A client provided request identifier.
// swagger:model ClientRequestID
type ClientRequestID string

// Validate validates this client request ID
func (m ClientRequestID) Validate(formats strfmt.Registry) error {
	return nil
}
