// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GuaranteedStopLossOrderLevelRestriction A GuaranteedStopLossOrderLevelRestriction represents the total position size that can exist within a given price window for Trades with guaranteed Stop Loss Orders attached for a specific Instrument.
// swagger:model GuaranteedStopLossOrderLevelRestriction
type GuaranteedStopLossOrderLevelRestriction struct {

	// The price range the volume applies to. This value is in price units.
	PriceRange string `json:"priceRange,omitempty"`

	// Applies to Trades with a guaranteed Stop Loss Order attached for the specified Instrument. This is the total allowed Trade volume that can exist within the priceRange based on the trigger prices of the guaranteed Stop Loss Orders.
	Volume string `json:"volume,omitempty"`
}

// Validate validates this guaranteed stop loss order level restriction
func (m *GuaranteedStopLossOrderLevelRestriction) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GuaranteedStopLossOrderLevelRestriction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GuaranteedStopLossOrderLevelRestriction) UnmarshalBinary(b []byte) error {
	var res GuaranteedStopLossOrderLevelRestriction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
